name: Java CI

on:
  push:
    branches: [main]  # 触发构建的分支
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # 检出代码

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # 设置 Java 版本
          distribution: 'adopt'  # 使用 AdoptOpenJDK

      - name: Build with Maven
        run: mvn -B package --file pom.xml  # 使用 Maven 构建项目

      - name: Run Tests
        run: mvn test  # 运行测试

      - name: Display Build Output
        run: echo "Build completed successfully!"
